// Command pcscfloopback validates the whole P-CSCF discovery mechanism
// (RFC 7651 IKEv2 configuration attributes -> p_cscf_vohive charon plugin
// -> pcscfbridge -> engine/swu.Session.PCSCFAddr()) against a REAL charon
// process, not a fake. It reuses the same charon-talking-to-itself PSK
// loopback shape already validated in spike/vicispike/loopback/main.go (see
// that file and MAPPING.md for why PSK, not EAP-AKA, is used to exercise
// tunnel mechanics cheaply on this box).
//
// The one piece that can't come from engine/swu.Manager/Dial directly is
// the *responder* side of P-CSCF: something has to actually answer the
// CFG_REQUEST with a P_CSCF_IP4_ADDRESS attribute. strongSwan's own stock
// `attr` plugin can do exactly that (as a static per-connection responder
// config, `charon.plugins.attr.p-cscf = <ip>`) -- since this is a
// self-connection, the *same* charon process plays both roles, so loading
// that one extra stock-plugin setting alongside our own p-cscf-vohive
// handler is enough to prove the full CFG_REQUEST -> CFG_REPLY -> handle()
// -> push -> Bridge.WaitFor() round trip for real.
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/strongswan/govici/vici"

	"github.com/1239t/vowifi-go/engine/swu/charon"
	"github.com/1239t/vowifi-go/engine/swu/pcscfbridge"
)

const wantPCSCFIP = "203.0.113.66"

// attrConfPath is a second, separate strongswan.d fragment (not part of
// charon.Supervisor's own template) enabling the stock `attr` plugin's
// static P-CSCF responder config -- see the package doc comment above.
const attrConfPath = "/etc/strongswan.d/93-vohive-pcscf-loopback-attr.conf"

func main() {
	if err := os.WriteFile(attrConfPath, []byte(fmt.Sprintf(
		"# generated by spike/pcscfloopback -- do not commit\ncharon {\n    plugins {\n        attr {\n            p-cscf = %s\n        }\n    }\n}\n",
		wantPCSCFIP,
	)), 0o644); err != nil {
		log.Fatalf("write attr conf fragment: %v", err)
	}
	defer os.Remove(attrConfPath)

	bridge := pcscfbridge.New()
	bridgeCtx, bridgeCancel := context.WithCancel(context.Background())
	bridgeDone := make(chan struct{})
	socketPath := "/run/charon.vohive-pcscf-looptest"
	go func() {
		defer close(bridgeDone)
		if err := bridge.ListenAndServe(bridgeCtx, socketPath); err != nil {
			log.Printf("bridge.ListenAndServe: %v", err)
		}
	}()
	defer func() {
		bridgeCancel()
		<-bridgeDone
	}()

	sup, err := charon.NewSupervisor(charon.Options{
		RunDir:                "/tmp/vohive-pcscf-looptest-run",
		ConfFragmentPath:      "/etc/strongswan.d/92-vohive-pcscf-looptest.conf",
		AKABridgeSocketPath:   "/run/charon.vohive-aka-looptest",
		PCSCFBridgeSocketPath: socketPath,
	})
	if err != nil {
		log.Fatalf("new supervisor: %v", err)
	}

	startCtx, startCancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer startCancel()
	if err := sup.Start(startCtx); err != nil {
		log.Fatalf("start charon: %v", err)
	}
	fmt.Println("charon started with eap-aka-vohive + p-cscf-vohive loaded")
	defer func() {
		stopCtx, stopCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer stopCancel()
		if err := sup.Stop(stopCtx); err != nil {
			log.Printf("stop charon: %v", err)
		}
	}()

	s, err := sup.Session()
	if err != nil {
		log.Fatalf("vici session: %v", err)
	}
	defer s.Close()

	secretMsg := vici.NewMessage()
	_ = secretMsg.Set("type", "ike")
	_ = secretMsg.Set("data", "spike-pcscf-loopback-psk-not-for-real-use")
	resp, err := s.Call(context.Background(), "load-shared", secretMsg)
	if err != nil {
		log.Fatalf("load-shared call: %v", err)
	}
	if err := resp.Err(); err != nil {
		log.Fatalf("load-shared rejected: %v", err)
	}

	type child struct {
		ESPProposals []string `vici:"esp_proposals"`
		LocalTS      []string `vici:"local_ts"`
		RemoteTS     []string `vici:"remote_ts"`
		Mode         string   `vici:"mode"`
		StartAction  string   `vici:"start_action"`
	}
	type pool struct {
		Addrs string `vici:"addrs"`
	}
	poolMsg, err := vici.MarshalMessage(map[string]pool{"pcscf-loopback-pool": {Addrs: "10.98.0.0/28"}})
	if err != nil {
		log.Fatalf("marshal pool: %v", err)
	}
	resp, err = s.Call(context.Background(), "load-pool", poolMsg)
	if err != nil {
		log.Fatalf("load-pool call: %v", err)
	}
	if err := resp.Err(); err != nil {
		log.Fatalf("load-pool rejected: %v", err)
	}

	type localAuth struct {
		Auth string `vici:"auth"`
	}
	type conn struct {
		Version     string           `vici:"version"`
		LocalAddrs  []string         `vici:"local_addrs"`
		RemoteAddrs []string         `vici:"remote_addrs"`
		Proposals   []string         `vici:"proposals"`
		Vips        []string         `vici:"vips"`
		Pools       []string         `vici:"pools"`
		Local1      localAuth        `vici:"local-1"`
		Remote1     localAuth        `vici:"remote-1"`
		Children    map[string]child `vici:"children"`
	}
	const connName = "pcscf-loopback"
	c := conn{
		Version:     "2",
		LocalAddrs:  []string{"127.0.0.1"},
		RemoteAddrs: []string{"127.0.0.1"},
		Proposals:   []string{"default"},
		Vips:        []string{"0.0.0.0"},
		Pools:       []string{"pcscf-loopback-pool"},
		Local1:      localAuth{Auth: "psk"},
		Remote1:     localAuth{Auth: "psk"},
		Children: map[string]child{
			"lo": {
				ESPProposals: []string{"default"},
				LocalTS:      []string{"0.0.0.0/0"},
				RemoteTS:     []string{"0.0.0.0/0"},
				Mode:         "tunnel",
				StartAction:  "none",
			},
		},
	}
	loadMsg, err := vici.MarshalMessage(map[string]conn{connName: c})
	if err != nil {
		log.Fatalf("marshal: %v", err)
	}
	resp, err = s.Call(context.Background(), "load-conn", loadMsg)
	if err != nil {
		log.Fatalf("load-conn call: %v", err)
	}
	if err := resp.Err(); err != nil {
		log.Fatalf("load-conn rejected: %v", err)
	}
	fmt.Println("load-conn ok")

	pushCh := bridge.WaitFor(connName)
	defer bridge.Forget(connName)

	initMsg := vici.NewMessage()
	_ = initMsg.Set("ike", connName)
	_ = initMsg.Set("child", "lo")
	_ = initMsg.Set("timeout", "5000")

	initCtx, initCancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer initCancel()
	for m, err := range s.CallStreaming(initCtx, "initiate", "control-log", initMsg) {
		if err != nil {
			log.Printf("initiate ended: %v", err)
			break
		}
		_ = m
	}

	var gotIP string
	select {
	case ip := <-pushCh:
		gotIP = ip.String()
		fmt.Printf("pcscfbridge received push: %s\n", gotIP)
	case <-time.After(5 * time.Second):
		fmt.Println("FAIL: no P-CSCF push received within 5s")
	}

	termMsg := vici.NewMessage()
	_ = termMsg.Set("ike", connName)
	termCtx, termCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer termCancel()
	for range s.CallStreaming(termCtx, "terminate", "control-log", termMsg) {
	}

	unloadMsg := vici.NewMessage()
	_ = unloadMsg.Set("name", connName)
	_, _ = s.Call(context.Background(), "unload-conn", unloadMsg)

	fmt.Println()
	if gotIP == wantPCSCFIP {
		fmt.Printf("PASS: real charon + p_cscf_vohive plugin + pcscfbridge delivered the correct P-CSCF address (%s) end to end\n", gotIP)
	} else {
		log.Fatalf("FAIL: got P-CSCF IP %q, want %q", gotIP, wantPCSCFIP)
	}
}
